### Number Arrays Operations


In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing: ", arr[2:7])
print("Step Slicing: ", arr[1:10:2])
print("Negative Slicing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
Step Slicing:  [ 2  4  6  8 10]
Negative Slicing:  8


In [9]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Specific Element: ", arr_2d[1:2])   #1st matrix 2nd digit according to indexing
print("Entire Row: ", arr_2d[2])
print("Specific Column: ", arr_2d[:, 1])


Specific Element:  [[4 5 6]]
Entire Row:  [7 8 9]
Specific Column:  [2 5 8]


### Sorting

In [12]:
unsorted = np.array([2, 1, 4, 3, 6, 10])
print("Sorted Array: ", np.sort(unsorted))

unsorted_2d_array = np.array([[1, 3], [2, 3], [4, 1]])
print("Sorted 2D arrays by column: ", np.sort(unsorted_2d_array, axis= 0))

Sorted Array:  [ 1  2  3  4  6 10]
Sorted 2D arrays by column:  [[1 1]
 [2 3]
 [4 3]]


## Filter

In [14]:
number = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = number[ number % 2 == 0]
print("Even Number", even_number)

Even Number [ 2  4  6  8 10]


### Filter with mask

In [16]:
mask = number > 5
print("Number greater than 5", number[mask]) # mask gives the evaluated value 

Number greater than 5 [ 6  7  8  9 10]


### Adding and Removing data

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

Combined = np.concatenate((arr1, arr2))
print(Combined)

[1 2 3 4 5 6]


In [24]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row)) #vstack is used to add new array in a row vertically 
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("original col", original)
print("new col", with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
original col [[1 2]
 [3 4]]
new col [[1 2 7]
 [3 4 8]]
