## Numpy Array and Basics

Learn About Numpy

In [1]:
import numpy as np

### Creating array from list    

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1d_array:" , arr_1d)

arr_2d = np.array([[1, 2, 3] , [4, 5, 6]])
print("2d_array:" , arr_2d)

1d_array: [1 2 3 4 5]
2d_array: [[1 2 3]
 [4 5 6]]


### List vs array

In [8]:
list_py = [1, 2, 3]
print("Python list multiplication", list_py * 2)

list_numpy = np.array([1, 2, 3])  
print("Numpy list multiplication", list_numpy * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Python List operation time: ", time.time() - start)

start = time.time()
np.array = np.arange(1000000) * 2
print("\n Numpy List operation time: ", time.time() - start)




Python list multiplication [1, 2, 3, 1, 2, 3]
Numpy list multiplication [2 4 6]

 Python List operation time:  0.24951887130737305

 Numpy List operation time:  0.0077021121978759766


### Creating array from scratch

In [21]:
Ones = np.ones((2,3))
print("Ones Array: \n", Ones)

Zeros = np.zeros((2,3))
print("Zeros Array: \n", Zeros)

Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Zeros Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]


### Vectors, Matrices and Tensor

In [ ]:
vector = np.array([1, 2, 3, 4, 5])  # 1D Array
print("Vector: ", vector)

Matrix = np.array([[1,2], [3,4]])  # 2D Arrays
print("Matrix: ", Matrix)

Tensor = np.array([[[1,2], [3,4]],[[5,6], [6,7]]]) # Combination of vector and Matrices
print("Tensor: ", Tensor)

Vector:  [1 2 3 4 5]
Matrix:  [[1 2]
 [3 4]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


### Array properties

In [8]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print("Shape" , arr.shape)
print("Size" , arr.size)
print("Dimesion" , arr.ndim)
print("Data Type" , arr.dtype)

Shape (2, 3)
Size 6
Dimesion 2
Data Type int64


### Array Resphaping

In [20]:
arr = np.arange(12)
print(arr)

Reshaped = arr.reshape(3, 4)
print("Reshaped Array: \n", Reshaped)

Transpose = Reshaped.T
print("Transposed Array: \n", Transpose)

flattened = Reshaped.flatten()
print("Flattened Array: \n", flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
